rm -rf ./tmp/*
echo "<?xml version='1.0' encoding='UTF-8' standalone='yes' ?><gpx version='1.1' xmlns='http://www.topografix.com/GPX/1/1'   width='2560' height='1280'  renderingProperties='appMode=default,groundSurveyMode=true,hmRendered=true,lang=en,contourLines=13'  renderingName='src/rendering/offroad-survey'>  <wpt lat='19.3619' lon='98.6302'>    <name>13</name>    <extensions>      <maps>Thailand_asia,Thailand_asia_22_01_00,Thailand_asia_22_02_00,Thailand_asia.srtm</maps>      <zoom>13</zoom>    </extensions>  </wpt></gpx>" > ./tmp/13.gpx
rm -rf ../../OSM/osm-tools/osmand-offroad-survey-plugin-preview/tiles
mkdir -p ../../OSM/osm-tools/osmand-offroad-survey-plugin-preview/tiles/13/6336
mkdir -p ../../OSM/osm-tools/osmand-offroad-survey-plugin-preview/tiles/13/6337
mkdir -p ../../OSM/osm-tools/osmand-offroad-survey-plugin-preview/tiles/13/6338
mkdir -p ../../OSM/osm-tools/osmand-offroad-survey-plugin-preview/tiles/13/6339
mkdir -p ../../OSM/osm-tools/osmand-offroad-survey-plugin-preview/tiles/13/6340
mkdir -p ../../OSM/osm-tools/osmand-offroad-survey-plugin-preview/tiles/13/6341
mkdir -p ../../OSM/osm-tools/osmand-offroad-survey-plugin-preview/tiles/13/6342
mkdir -p ../../OSM/osm-tools/osmand-offroad-survey-plugin-preview/tiles/13/6343
mkdir -p ../../OSM/osm-tools/osmand-offroad-survey-plugin-preview/tiles/13/6344
mkdir -p ../../OSM/osm-tools/osmand-offroad-survey-plugin-preview/tiles/13/6345
java -Xms64M -Xmx512M -cp ../OsmAndMapCreator-main/OsmAndMapCreator.jar net.osmand.swing.OsmAndImageRendering   -native=/Users/julien/Documents/WORKSPACE/OsmAnd/OsmAnd-core-legacy/binaries/darwin/intel/Release   -obfFiles=./obf/   -gpxFile=./tmp/13.gpx   -output=./tmp
convert ./tmp/13.png -crop 256x256 -set filename:tile "%[fx:page.x/256+6336]/%[fx:page.y/256+3644]" +repage "../../OSM/osm-tools/osmand-offroad-survey-plugin-preview/tiles/13/%[filename:tile].png"
echo "<!DOCTYPE html><html><head>  <title>OsmAnd Offroad-Survey Plugin Preview (Northern Thailand)</title>  <meta charset='utf-8' />  <meta name='viewport' content='width=device-width, initial-scale=1.0'>    <link rel='stylesheet' href='https://unpkg.com/leaflet@1.7.1/dist/leaflet.css' integrity='sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A==' crossorigin=''/>    <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css'>    <script src='https://unpkg.com/leaflet@1.7.1/dist/leaflet.js' integrity='sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA==' crossorigin=''></script>    <style>    html,body,#map{width:100%;height:100%;margin: 0; padding: 0;}  </style></head><body><div id='map'></div><script>  const zoom = 13;  const center = [ 19.3619, 98.6302 ];  const pluginLayer = L.tileLayer('./tiles/{z}/{x}/{y}.png?date=2022-02-06', {    attribution: '<a href="https://github.com/cmoffroad/osmand-offroad-survey-plugin">osmand-offroad-survey-plugin</a>'  });  var map = new L.Map('map', {     minZoom: zoom,     maxZoom: zoom,    maxBounds: L.latLngBounds(      L.latLng(19.45623359601799, 98.4375),      L.latLng(19.24892232846279, 98.876953125)    ),    layers: [ pluginLayer ]  })  .setView(center, zoom);  map.attributionControl.setPrefix('');  var baseLayers = {    'osmand-offroad-survey-plugin': pluginLayer,    'komoot': L.tileLayer('http://{s}.tile.komoot.de/komoot/{z}/{x}/{y}.png?lang=en'),    'cyclemap': L.tileLayer('https://{s}.tile.thunderforest.com/cycle/{z}/{x}/{y}.png?apikey=6170aad10dfd42a38d4d8c709a536f38'),    'mapy.cz': L.tileLayer('https://mapserver.mapy.cz/base-m/{z}-{x}-{y}?sdk=HgUbCgUbGkgqAQkYBxYEHQNHQlJfR1VfQlBZSw%3D%3D'),    'google (terrain)': L.tileLayer('https://mt3.Google.com/vt?z={z}&x={x}&y={y}&lyrs=p'),    'google (satellite)': L.tileLayer('https://mt3.Google.com/vt?z={z}&x={x}&y={y}&lyrs=y')  };  var overlays = {    'OSM GPS traces': L.tileLayer('https://{s}.gps-tile.openstreetmap.org/lines/{z}/{x}/{y}.png')  };  L.control.layers(baseLayers, overlays).addTo(map);</script></body></html>" > ../../OSM/osm-tools/osmand-offroad-survey-plugin-preview/index.html
open ../../OSM/osm-tools/osmand-offroad-survey-plugin-preview/index.html
